# Generated by Django 6.0 on 2025-12-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
