# Generated by Django 6.0 on 2025-12-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_message_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='surname',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
