from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MessageViewSet

# Create a router and register our ViewSets with it.
router = DefaultRouter()
router.register(r'messages', MessageViewSet) # The URL path will be /api/messages/

# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('', include(router.urls)),
]

"""
🗺️ The Role of tracker/urls.py (The API Map)
The tracker/urls.py file is the Application URL Configuration.
 Its primary job is to define the specific web addresses (URLs) within the tracker app that users or your frontend can hit, 
 and to map those addresses to the correct piece of code (MessageViewSet) that handles the request.

Your tracker/urls.py contains these lines:

Python

# tracker/urls.py

from rest_framework.routers import DefaultRouter
from .views import MessageViewSet

router = DefaultRouter()
router.register(r'messages', MessageViewSet) 

urlpatterns = [
    path('', include(router.urls)),
]
Here is what the file is achieving:

1. It Defines the Path Segments (router.register)
The line router.register(r'messages', MessageViewSet) is the heart of the file. It tells the Django framework:

"Any request coming into this application's base URL (which you defined as /api/ in the main project settings) 
followed by the segment /messages/ should be handled by the logic defined in the MessageViewSet."

2. It Manages Complexity (The Router)
Without DRF's DefaultRouter, you would have to manually create a list of path definitions in urlpatterns like this for a single model:

Python

# If we didn't use a router (Manual way)
urlpatterns = [
    # List and Create
    path('messages/', MessageViewSet.as_view({'get': 'list', 'post': 'create'})),
    # Retrieve, Update, and Destroy
    path('messages/<int:pk>/', MessageViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
]
The router eliminates all that manual work. The tracker/urls.py file is essentially a container for the DefaultRouter, 
which automatically converts your single router.register() line into the 7 or more individual path definitions shown above.

3. It Integrates into the Project (urlpatterns)
The final part, urlpatterns = [path('', include(router.urls))], is responsible for taking all the automatic URLs generated by the router and 
making them available when the main project's backend/urls.py points to this file.

In Summary
The tracker/urls.py file:

Acts as the API's map. It defines the specific address (the endpoint, e.g., /messages/) for your resource.

Uses the DefaultRouter to efficiently generate all necessary CRUD paths based on your single MessageViewSet.

Completes the URL chain: It combines with the main project's URL file to create the full, accessible path: /api/messages/.
URL configuration for tracker app."""