# Generated by Django 6.0 on 2026-01-21 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=200)),
                ('drawing_number', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(choices=[('avatar1', 'Avatar 1'), ('avatar2', 'Avatar 2'), ('avatar3', 'Avatar 3'), ('avatar4', 'Avatar 4'), ('avatar5', 'Avatar 5'), ('avatar6', 'Avatar 6'), ('avatar7', 'Avatar 7'), ('avatar8', 'Avatar 8'), ('avatar9', 'Avatar 9'), ('avatar10', 'Avatar 10'), ('avatar11', 'Avatar 11'), ('avatar12', 'Avatar 12'), ('avatar13', 'Avatar 13'), ('avatar14', 'Avatar 14'), ('avatar15', 'Avatar 15'), ('avatar16', 'Avatar 16'), ('avatar17', 'Avatar 17'), ('avatar18', 'Avatar 18'), ('avatar19', 'Avatar 19'), ('avatar20', 'Avatar 20')], default='avatar1', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
