# Generated by Django 6.0 on 2026-01-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
