# Generated by Django 6.0 on 2026-01-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobs_finished_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='costumer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='operador',
            new_name='operator',
        ),
    ]
