# Generated by Django 6.0 on 2026-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_costumer_jobs_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In progress'), ('finished', 'Finished')], default='in_progress', max_length=20),
        ),
    ]
